// @ts-check
/** Chinese (Simplified) docs (partial tree); expand as `docs-zh/` grows.
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		{ type: "doc", id: "intro", label: "主页" },
		{
			type: "category",
			label: "车辆核验",
			items: [{ type: "autogenerated", dirName: "vehicle-validation" }],
		},
		{
			type: "category",
			label: "身份核验",
			items: [{ type: "autogenerated", dirName: "identity" }],
		},
		{
			type: "category",
			label: "企业(KYB)",
			items: [{ type: "autogenerated", dirName: "business-validation" }],
		},
		{
			type: "category",
			label: "背景调查",
			collapsible: false,
			items: [
				{ type: "doc", id: "background-check/brazil", label: "🇧🇷 巴西" },
				{ type: "doc", id: "background-check/colombia-public-contracts", label: "🇨🇴 公共合同" },
				{ type: "doc", id: "background-check/colombia-police-record-check", label: "🇨🇴 警方犯罪记录" },
				{ type: "doc", id: "background-check/colombia-police-compliance-corrective-measures", label: "🇨🇴 RNMC 纠正措施" },
				{ type: "doc", id: "background-check/colombia-comptroller-certificate", label: "🇨🇴 审计署证明" },
				{ type: "doc", id: "background-check/colombia-disciplinary-records-attorneys-office", label: "🇨🇴 纪律处分记录" },
				{ type: "doc", id: "background-check/colombia-inpec", label: "🇨🇴 INPEC" },
				{ type: "doc", id: "background-check/dea-background-check", label: "🌐 DEA" },
				{ type: "doc", id: "background-check/europol-background-check", label: "🌐 Europol" },
				{ type: "doc", id: "background-check/fbi-background-check", label: "🌐 FBI" },
				{ type: "doc", id: "background-check/interpol-background-check", label: "🌐 Interpol" },
				{ type: "doc", id: "background-check/ofac-background-check", label: "🌐 OFAC" },
				{ type: "doc", id: "background-check/onu-background-check", label: "🌐 ONU" },
			],
		},
	],
};

export default sidebars;
