// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Spanish sidebar configuration for Zelf Documentation
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	// Spanish sidebar structure
	tutorialSidebar: [
		{
			type: "doc",
			id: "intro",
			label: "Bienvenido a Verifik",
		},
		{
			type: "category",
			label: "AUTENTICACIÓN",
			collapsible: false,
			items: [
				"autenticacion/api-key-acceso-por-email",
				"autenticacion/api-key-acceso-por-telefono",
				"autenticacion/renovar-tu-token-jwt",
				"autenticacion/crear-nuevo-token-y-revocar-tokens-previos",
			],
		},
		{
			type: "category",
			label: "CLIENTES",
			collapsible: false,
			items: ["clients/informacion-cuenta"],
		},
		{
			type: "category",
			label: "SERVICIOS",
			collapsible: false,
			items: [
				"smartcheck/verificacion-inteligente",
				"smartaccess/acceso-inteligente",
				"access/acceso",
				"smartenroll/smartenroll",
				"smart-enroll-auto-alojado/smart-enroll-self-hosted",
				"smart-scan/escaneo-inteligente",
			],
		},
		{
			type: "category",
			label: "BIOMETRICS API'S",
			collapsible: false,
			items: [
				"biometrics/deteccion-vitalidad",
				{
					type: "category",
					label: "Comparación Facial",
					collapsible: true,
					items: ["biometrics/comparar", "biometrics/comparar-en-vivo", "biometrics/comparar-con-deteccion-vitalidad"],
				},
				{
					type: "category",
					label: "Búsqueda Facial",
					collapsible: true,
					items: ["biometrics/buscar", "biometrics/buscar-cara-en-vivo", "biometrics/buscar-usuario-activo", "biometrics/buscar-recortes"],
				},
				{
					type: "category",
					label: "Pruebas Faciales de Conocimiento Cero",
					collapsible: true,
					items: [
						"biometrics/pruebas-faciales-conocimiento-cero-resumen",
						"biometrics/pruebas-faciales-conocimiento-cero-encriptar",
						"biometrics/pruebas-faciales-conocimiento-cero-encriptar-codigo-qr",
						"biometrics/pruebas-faciales-conocimiento-cero-desencriptar",
						"biometrics/pruebas-faciales-conocimiento-cero-vista-previa",
					],
				},
			],
		},
		{
			type: "category",
			label: "SCAN DOCS API'S",
			collapsible: false,
			items: ["ocr-engines/escaneo-estudio", "ocr-engines/escaneo-prompt"],
		},
		{
			type: "category",
			label: "VERIFICACIÓN DE IDENTIDAD",
			link: {
				type: "doc",
				id: "identity/verificacion-identidad",
			},
			collapsible: false,
			items: [
				{ type: "doc", id: "identity/argentina", label: "🇦🇷 Argentina", key: "identity-argentina" },
				{ type: "doc", id: "identity/bolivia", label: "🇧🇴 Bolivia", key: "identity-bolivia" },
				{ type: "doc", id: "identity/brazil", label: "🇧🇷 Brasil", key: "identity-brazil" },
				{ type: "doc", id: "identity/canada", label: "🇨🇦 Canadá", key: "identity-canada" },
				{ type: "doc", id: "identity/chile", label: "🇨🇱 Chile", key: "identity-chile" },
				{ type: "doc", id: "identity/colombia", label: "🇨🇴 Ciudadano Colombiano" },
				{ type: "doc", id: "identity/colombia-full-id", label: "🇨🇴 Colombia - ID Completo" },
				{ type: "doc", id: "identity/colombia-ce", label: "🇨🇴 Colombia - CE" },
				{ type: "doc", id: "identity/colombia-pep-id", label: "🇨🇴 Colombia - ID PEP" },
				{ type: "doc", id: "identity/colombia-ppt", label: "🇨🇴 Colombia - PPT" },
				{ type: "doc", id: "identity/costa-rica", label: "🇨🇷 Costa Rica", key: "identity-costa-rica" },
				{ type: "doc", id: "identity/dominican-republic", label: "🇩🇴 República Dominicana", key: "identity-dominican-republic" },
				{ type: "doc", id: "identity/ecuador", label: "🇪🇨 Ecuador", key: "identity-ecuador" },
				{ type: "doc", id: "identity/el-salvador", label: "🇸🇻 El Salvador" },
				{ type: "doc", id: "identity/guatemala", label: "🇬🇹 Guatemala" },
				{ type: "doc", id: "identity/honduras", label: "🇭🇳 Honduras" },
				{ type: "doc", id: "identity/mexico", label: "🇲🇽 México", key: "identity-mexico" },
				{ type: "doc", id: "identity/panama", label: "🇵🇦 Panamá", key: "identity-panama" },
				{ type: "doc", id: "identity/paraguay", label: "🇵🇾 Paraguay", key: "identity-paraguay" },
				{ type: "doc", id: "identity/peru", label: "🇵🇪 Perú", key: "identity-peru" },
				{ type: "doc", id: "identity/peru-foreigner-id", label: "🇵🇪 Perú - Cédula de Extranjero" },
				{ type: "doc", id: "identity/peru-full-id", label: "🇵🇪 Perú - ID Completo" },
				{ type: "doc", id: "identity/spain-citizen", label: "🇪🇸 Ciudadano Español" },
				{ type: "doc", id: "identity/estados-unidos", label: "🇺🇸 Estados Unidos", key: "identity-estados-unidos" },
				{ type: "doc", id: "identity/uruguay", label: "🇺🇾 Uruguay" },
				{ type: "doc", id: "identity/venezuela", label: "🇻🇪 Venezuela" },
				{ type: "doc", id: "identity/venezuela-foreigner-id", label: "🇻🇪 Venezuela - Cédula de Extranjero" },
			],
		},
		{
			type: "category",
			label: "VALIDACIÓN EMPRESARIAL",
			link: {
				type: "doc",
				id: "validacion-empresarial/verificacion-empresarial",
			},
			collapsible: false,
			items: [
				{
					type: "doc",
					id: "validacion-empresarial/argentina",
					label: "🇦🇷 Argentina",
					key: "empresarial-argentina",
				},
				{
					type: "doc",
					id: "validacion-empresarial/bolivia",
					label: "🇧🇴 Bolivia",
					key: "empresarial-bolivia",
				},
				{
					type: "doc",
					id: "validacion-empresarial/brazil",
					label: "🇧🇷 Brasil",
					key: "empresarial-brazil",
				},
				{
					type: "doc",
					id: "validacion-empresarial/canada",
					label: "🇨🇦 Canadá",
					key: "empresarial-canada",
				},
				{
					type: "doc",
					id: "validacion-empresarial/chilean",
					label: "🇨🇱 Chile",
					key: "empresarial-chile",
				},
				{
					type: "doc",
					id: "validacion-empresarial/colombia-verificacion-dian",
					label: "🇨🇴 Colombia - Verificación DIAN",
				},
				{
					type: "doc",
					id: "validacion-empresarial/colombia-verificacion-facturador-legal",
					label: "🇨🇴 Colombia - Verificación Facturador Legal",
				},
				{
					type: "doc",
					id: "validacion-empresarial/colombia-validacion-empresarial-rues-completa-v3",
					label: "🇨🇴 Validación Empresarial RUES",
				},
				{
					type: "doc",
					id: "validacion-empresarial/costa-rica-empresarial",
					label: "🇨🇷 Costa Rica",
					key: "empresarial-costa-rica",
				},
				{
					type: "doc",
					id: "validacion-empresarial/mexico",
					label: "🇲🇽 México",
					key: "empresarial-mexico",
				},
				{
					type: "doc",
					id: "validacion-empresarial/panama",
					label: "🇵🇦 Panamá",
					key: "empresarial-panama",
				},
				{
					type: "doc",
					id: "validacion-empresarial/paraguay",
					label: "🇵🇾 Paraguay",
					key: "empresarial-paraguay",
				},
				{
					type: "doc",
					id: "validacion-empresarial/peru",
					label: "🇵🇪 Perú",
					key: "empresarial-peru",
				},
				{
					type: "doc",
					id: "validacion-empresarial/spain",
					label: "🇪🇸 España",
				},
				{
					type: "doc",
					id: "validacion-empresarial/united-states",
					label: "🇺🇸 Estados Unidos",
					key: "empresarial-estados-unidos",
				},
			],
		},
		{
			type: "category",
			label: "VALIDACIÓN DE LICENCIAS DE MANEJO",
			collapsible: false,
			items: [
				{
					type: "doc",
					id: "validaciones-conductores/chile-licencia-conducir",
					label: "🇨🇱 Chile - Licencia de Conducir",
				},
				{
					type: "doc",
					id: "validaciones-conductores/licencia-conducir-british-columbia",
					label: "🇨🇦 Canadá - Licencia de Conducir British Columbia",
				},
				{
					type: "doc",
					id: "validaciones-vehiculos/licencia-de-manejo-florida",
					label: "🇺🇸 Florida - Licencia de Manejo",
				},
				{
					type: "doc",
					id: "validaciones-vehiculos/licencia-de-manejo-kansas",
					label: "🇺🇸 Kansas - Licencia de Manejo",
				},
				{
					type: "doc",
					id: "validaciones-vehiculos/licencia-de-manejo-ontario",
					label: "🇨🇦 Ontario - Licencia de Manejo",
				},
			],
		},
		{
			type: "category",
			label: "VALIDACIÓN DE VEHÍCULOS",
			link: {
				type: "doc",
				id: "validacion-vehiculos/verificacion-vehiculos",
			},
			collapsible: false,
			items: [
				{
					type: "doc",
					id: "validacion-vehiculos/argentina",
					label: "🇦🇷 Argentina",
					key: "vehiculos-argentina",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/bolivia",
					label: "🇧🇴 Bolivia",
					key: "vehiculos-bolivia",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/brazil",
					label: "🇧🇷 Brasil",
					key: "vehiculos-brazil",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/chile",
					label: "🇨🇱 Chile",
					key: "vehiculos-chile",
				},
				{
					type: "category",
					label: "🇨🇴 Colombia",
					collapsible: true,
					items: [
						{
							type: "doc",
							id: "validacion-vehiculos/colombia",
							label: "Resumen",
							key: "vehiculos-colombia-resumen",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/impuestos-bogota",
							label: "Impuestos en Bogotá",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/multas-vehiculos-bogota",
							label: "Verificación de Multas de Vehículos",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/accidentalidad-vehiculos-bogota",
							label: "Accidentalidad de Vehículos",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/pico-y-placa-bogota",
							label: "Pico y Placa",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/valores-vehiculos-por-placa-fasecolda",
							label: "Valores de Vehículos por Placa",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/vehiculo-por-codigo-fasecolda",
							label: "Vehículo por Código",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/verificacion-siniestros-fasecolda",
							label: "Verificación de Siniestros",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/licencia-conducir-runt",
							label: "Licencia de Conducir",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/registros-vehiculos-por-placa-runt",
							label: "Registros de Vehículos por Placa",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/registros-vehiculos-por-placa-simplificado-runt",
							label: "Registros de Vehículos por Placa (Simplificado)",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/registros-vehiculos-por-vin-runt",
							label: "Registros de Vehículos por VIN",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/soat-rtm-vehiculo-runt",
							label: "SOAT y RTM del Vehículo",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/colombia-runt-soat-rtm",
							label: "RUNT - SOAT y RTM",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/multas-simit",
							label: "SIMIT - Multas",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/acuerdos-simit",
							label: "SIMIT - Acuerdos",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/resoluciones-simit",
							label: "SIMIT - Resoluciones",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/consulta-general-por-documento-simit",
							label: "Consulta General por Documento",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/consulta-general-por-placa-simit",
							label: "Consulta General por Placa",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/colombia/registros-entrenamiento-sisconmp",
							label: "Registros de Entrenamiento SISCONMP",
						},
					],
				},
				{
					type: "doc",
					id: "validacion-vehiculos/costa-rica",
					label: "🇨🇷 Costa Rica",
					key: "vehiculos-costa-rica",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/ecuador",
					label: "🇪🇨 Ecuador",
					key: "vehiculos-ecuador",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/mexico",
					label: "🇲🇽 México",
					key: "vehiculos-mexico",
				},
				{
					type: "doc",
					id: "validacion-vehiculos/paraguay",
					label: "🇵🇾 Paraguay",
					key: "vehiculos-paraguay",
				},
				{
					type: "category",
					label: "🇵🇪 Perú",
					collapsible: true,
					items: [
						{
							type: "doc",
							id: "validacion-vehiculos/peru",
							label: "Resumen",
							key: "vehiculos-peru-resumen",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/peru/peru-informacion-vehiculo",
							label: "Información de Vehículo",
						},
						{
							type: "doc",
							id: "validacion-vehiculos/peru/peru-seguro-vehiculo",
							label: "Seguro de Vehículo",
						},
					],
				},
				{
					type: "doc",
					id: "validacion-vehiculos/estados-unidos",
					label: "🇺🇸 Estados Unidos",
					key: "vehiculos-estados-unidos",
				},
			],
		},
		{
			type: "category",
			label: "VERIFICACIÓN DE ANTECEDENTES",
			collapsible: false,
			items: [
				"verificacion-antecendentes/tipos-documento",
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-brasil",
					label: "🇧🇷 Brasil - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-contratos-publicos",
					label: "🇨🇴 Colombia - Contratos Públicos",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-policia",
					label: "🇨🇴 Colombia - Antecedentes Policiales",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-cumplimiento-policial",
					label: "🇨🇴 Colombia - Cumplimiento Policial",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-contraloria",
					label: "🇨🇴 Colombia - Contraloría",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-procuraduria",
					label: "🇨🇴 Colombia - Procuraduría",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-colombia-inpec",
					label: "🇨🇴 Colombia - INPEC",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-europol",
					label: "🌐 Europol - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-dea",
					label: "🌐 DEA - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-fbi",
					label: "🌐 FBI - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-interpol",
					label: "🌐 Interpol - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-ofac",
					label: "🌐 OFAC - Antecedentes",
				},
				{
					type: "doc",
					id: "verificacion-antecendentes/verificacion-antecendentes-onu",
					label: "🌐 ONU - Antecedentes",
				},
			],
		},
		{
			type: "category",
			label: "VOTACIÓN",
			collapsible: false,
			items: ["legal/votacion"],
		},
		{
			type: "category",
			label: "SALUD",
			collapsible: false,
			items: ["legal/salud", "legal/verificar-afiliaciones-colombianas"],
		},
		{
			type: "category",
			label: "VERIFICACIONES LEGALES",
			collapsible: false,
			items: [
				{
					type: "doc",
					id: "legal/verificacion-abogados",
					label: "🇨🇴 Verificación de Abogado Colombiano",
				},
				{
					type: "doc",
					id: "legal/procesos-legales-colombianos",
					label: "🇨🇴 Procesos Legales Colombianos",
				},
				{
					type: "doc",
					id: "legal/recuperar-detalles-proceso-legal-por-numero",
					label: "🇨🇴 Detalles de Proceso Legal Colombiano",
				},
				{
					type: "doc",
					id: "legal/certificado-vigencia-profesionales-legales",
					label: "🇨🇴 Vigencia de Profesionales Legales Colombianos",
				},
				{
					type: "doc",
					id: "legal/sigep-servidor-publico-por-numero",
					label: "🇨🇴 Colombia - Consulta de Servidor Público por Número (SIGEP)",
				},
				{
					type: "doc",
					id: "legal/sigep-servidor-publico-por-nombre",
					label: "🇨🇴 Colombia - Consulta de Servidor Público por Nombre (SIGEP)",
				},
			],
		},
		{
			type: "category",
			label: "RECURSOS",
			collapsible: false,
			items: [
				{
					type: "category",
					label: "Proyectos",
					key: "resources-proyectos",
					collapsible: true,
					items: [
						"resources/proyectos/el-objeto-proyecto",
						"resources/proyectos/crear-un-proyecto",
						"resources/proyectos/recuperar-un-proyecto",
						"resources/proyectos/listar-todos-los-proyectos",
						"resources/proyectos/actualizar-un-proyecto",
						"resources/proyectos/eliminar-un-proyecto",
					],
				},
				{
					type: "category",
					label: "Flujos de Proyecto",
					key: "resources-flujos-de-proyecto",
					collapsible: true,
					items: [
						"resources/flujos-de-proyecto/el-objeto-flujo-de-proyecto",
						"resources/flujos-de-proyecto/actualizar-un-flujo-de-proyecto",
						"resources/flujos-de-proyecto/eliminar-un-flujo-de-proyecto",
					],
				},
				{
					type: "category",
					label: "Inicios de Sesión de Aplicación",
					collapsible: true,
					items: [
						"resources/inicios-sesion-aplicacion/inicios-sesion-aplicacion",
						"resources/inicios-sesion-aplicacion/el-objeto-inicio-sesion-aplicacion",
						"resources/inicios-sesion-aplicacion/crear-un-inicio-sesion-aplicacion",
						"resources/inicios-sesion-aplicacion/recuperar-un-inicio-sesion-aplicacion",
						"resources/inicios-sesion-aplicacion/listar-todos-los-inicios-sesion-aplicacion",
						"resources/inicios-sesion-aplicacion/crear-una-validacion-biometrica-inicio-sesion-aplicacion",
						"resources/inicios-sesion-aplicacion/validar-una-validacion-biometrica-inicio-sesion-aplicacion",
						"resources/inicios-sesion-aplicacion/ejemplo-acceso-por-email",
					],
				},
				{
					type: "category",
					label: "Registros de Aplicación",
					collapsible: true,
					items: [
						"resources/registros-aplicacion/registros-aplicacion",
						"resources/registros-aplicacion/el-objeto-registro-aplicacion",
						"resources/registros-aplicacion/crear-un-registro-aplicacion",
						"resources/registros-aplicacion/recuperar-un-registro-aplicacion",
						"resources/registros-aplicacion/listar-todos-los-registros-aplicacion",
						"resources/registros-aplicacion/crear-una-validacion-biometrica-registro-aplicacion",
						"resources/registros-aplicacion/crear-una-validacion-documento-registro-aplicacion",
						"resources/registros-aplicacion/crear-una-validacion-email-registro-aplicacion",
						"resources/registros-aplicacion/crear-una-validacion-telefono-registro-aplicacion",
						"resources/registros-aplicacion/validar-una-validacion-email-registro-aplicacion",
						"resources/registros-aplicacion/validar-una-validacion-telefono-registro-aplicacion",
						"resources/registros-aplicacion/sincronizar-estado-registro-aplicacion",
					],
				},
				{
					type: "category",
					label: "Validaciones Biométricas",
					collapsible: true,
					items: [
						"resources/validaciones-biometricas/validaciones-biometricas",
						"resources/validaciones-biometricas/el-objeto-validacion-biometrica",
						"resources/validaciones-biometricas/crear-una-validacion-biometrica",
						"resources/validaciones-biometricas/recuperar-una-validacion-biometrica",
						"resources/validaciones-biometricas/listar-todas-las-validaciones-biometricas",
					],
				},
				{
					type: "category",
					label: "Colecciones",
					collapsible: true,
					items: [
						"resources/colecciones/el-objeto-coleccion",
						"resources/colecciones/crear-una-coleccion",
						"resources/colecciones/listar-todas-las-colecciones",
						"resources/colecciones/recuperar-una-coleccion",
					],
				},
				{
					type: "category",
					label: "Créditos",
					collapsible: true,
					items: [
						"resources/creditos/creditos",
						"resources/creditos/el-objeto-credito",
						"resources/creditos/listar-todos-los-registros-credito",
						"resources/creditos/recuperar-un-registro-credito",
					],
				},
				{
					type: "category",
					label: "Vivacidad de Documentos",
					collapsible: true,
					items: [
						"resources/vivacidad-documentos/vivacidad-documentos",
						"resources/vivacidad-documentos/el-objeto-vivacidad-documento",
						"resources/vivacidad-documentos/crear-una-vivacidad-documento",
						"resources/vivacidad-documentos/recuperar-una-vivacidad-documento",
						"resources/vivacidad-documentos/listar-todas-las-vivacidades-documentos",
					],
				},
				{
					type: "category",
					label: "Validaciones de Documentos",
					collapsible: true,
					items: [
						"resources/validaciones-documentos/validaciones-documentos",
						"resources/validaciones-documentos/el-objeto-validacion-documento",
						"resources/validaciones-documentos/crear-una-validacion-nombre",
						"resources/validaciones-documentos/recuperar-una-validacion-documento",
						"resources/validaciones-documentos/listar-todas-las-validaciones-documentos",
						"resources/validaciones-documentos/actualizar-una-validacion-documento",
						"resources/validaciones-documentos/eliminar-una-validacion-documento",
					],
				},
				{
					type: "category",
					label: "Validaciones de Email",
					collapsible: true,
					items: [
						"resources/validaciones-email/validaciones-email",
						"resources/validaciones-email/el-objeto-validacion-email",
						"resources/validaciones-email/crear-una-validacion-email",
						"resources/validaciones-email/recuperar-una-validacion-email",
						"resources/validaciones-email/listar-todas-las-validaciones-email",
						"resources/validaciones-email/validar-una-validacion-email",
					],
				},
				{
					type: "category",
					label: "Personas",
					collapsible: true,
					items: [
						"resources/personas/personas",
						"resources/personas/el-objeto-persona",
						"resources/personas/crear-una-persona",
						"resources/personas/recuperar-una-persona",
						"resources/personas/listar-todas-las-personas",
					],
				},
				{
					type: "category",
					label: "Validaciones de Teléfono",
					collapsible: true,
					items: [
						"resources/validaciones-telefono/validaciones-telefono",
						"resources/validaciones-telefono/el-objeto-validacion-telefono",
						"resources/validaciones-telefono/crear-una-validacion-telefono",
						"resources/validaciones-telefono/recuperar-una-validacion-telefono",
						"resources/validaciones-telefono/listar-todas-las-validaciones-telefono",
						"resources/validaciones-telefono/validar-una-validacion-telefono",
						"phone-validations/sms-and-whatsapp-prices",
					],
				},
				{
					type: "category",
					label: "Tickets de Soporte",
					collapsible: true,
					items: [
						"resources/tickets-soporte/tickets-soporte",
						"resources/tickets-soporte/el-objeto-ticket-soporte",
						"resources/tickets-soporte/crear-un-ticket-soporte",
						"resources/tickets-soporte/recuperar-un-ticket-soporte",
						"resources/tickets-soporte/listar-todos-los-tickets-soporte",
					],
				},
				{
					type: "category",
					label: "Webhooks",
					collapsible: true,
					items: [
						"resources/webhooks/webhooks",
						"resources/webhooks/integracion-webhook",
						"resources/webhooks/el-objeto-webhook",
						"resources/webhooks/crear-un-webhook",
						"resources/webhooks/recuperar-un-webhook",
						"resources/webhooks/listar-todos-los-webhooks",
						"resources/webhooks/actualizar-un-webhook",
						"resources/webhooks/eliminar-un-webhook",
					],
				},
			],
		},
		{
			type: "category",
			label: "VERIFIK LLC",
			collapsible: false,
			items: [
				"legal/politica-privacidad",
				"legal/terminos-y-condiciones",
				"legal/acuerdo-de-niveles-de-servicio",
				"legal/verifik-for-enterprises-hub-esp",
				"legal/smartcheck-terminos-y-condiciones-de-uso",
			],
		},
	],
};

export default sidebars;
