// @ts-check
/** Japanese docs (partial tree); expand as `docs-ja/` grows.
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		{ type: "doc", id: "intro", label: "ホーム" },
		{
			type: "category",
			label: "車両検証",
			items: [{ type: "autogenerated", dirName: "vehicle-validation" }],
		},
		{
			type: "category",
			label: "本人確認",
			items: [{ type: "autogenerated", dirName: "identity" }],
		},
		{
			type: "category",
			label: "法人(KYB)",
			items: [{ type: "autogenerated", dirName: "business-validation" }],
		},
		{
			type: "category",
			label: "運転免許",
			items: [{ type: "autogenerated", dirName: "driver-validation" }],
		},
		{
			type: "category",
			label: "背景調査",
			collapsible: false,
			items: [
				{ type: "doc", id: "background-check/brazil", label: "🇧🇷 ブラジル" },
				{ type: "doc", id: "background-check/colombia-public-contracts", label: "🇨🇴 公共契約" },
				{ type: "doc", id: "background-check/colombia-police-record-check", label: "🇨🇴 警察の犯罪経歴" },
				{ type: "doc", id: "background-check/colombia-police-compliance-corrective-measures", label: "🇨🇴 RNMC 是正措置" },
				{ type: "doc", id: "background-check/colombia-comptroller-certificate", label: "🇨🇴 会計検査院証明" },
				{ type: "doc", id: "background-check/colombia-disciplinary-records-attorneys-office", label: "🇨🇴 懲戒記録" },
				{ type: "doc", id: "background-check/colombia-inpec", label: "🇨🇴 INPEC" },
				{ type: "doc", id: "background-check/dea-background-check", label: "🌐 DEA" },
				{ type: "doc", id: "background-check/europol-background-check", label: "🌐 Europol" },
				{ type: "doc", id: "background-check/fbi-background-check", label: "🌐 FBI" },
				{ type: "doc", id: "background-check/interpol-background-check", label: "🌐 Interpol" },
				{ type: "doc", id: "background-check/ofac-background-check", label: "🌐 OFAC" },
				{ type: "doc", id: "background-check/onu-background-check", label: "🌐 ONU" },
			],
		},
	],
};

export default sidebars;
