// @ts-check
/** Korean docs (partial tree); expand as `docs-ko/` grows.
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
	tutorialSidebar: [
		{ type: "doc", id: "intro", label: "홈" },
		{
			type: "category",
			label: "차량 검증",
			items: [{ type: "autogenerated", dirName: "vehicle-validation" }],
		},
		{
			type: "category",
			label: "신원",
			items: [{ type: "autogenerated", dirName: "identity" }],
		},
		{
			type: "category",
			label: "기업(KYB)",
			items: [{ type: "autogenerated", dirName: "business-validation" }],
		},
		{
			type: "category",
			label: "배경 조회",
			collapsible: false,
			items: [
				{ type: "doc", id: "background-check/brazil", label: "🇧🇷 브라질" },
				{ type: "doc", id: "background-check/colombia-public-contracts", label: "🇨🇴 공공 계약" },
				{ type: "doc", id: "background-check/colombia-police-record-check", label: "🇨🇴 경찰 범죄 경력" },
				{ type: "doc", id: "background-check/colombia-police-compliance-corrective-measures", label: "🇨🇴 RNMC 시정 조치" },
				{ type: "doc", id: "background-check/colombia-comptroller-certificate", label: "🇨🇴 감사원 증명" },
				{ type: "doc", id: "background-check/colombia-disciplinary-records-attorneys-office", label: "🇨🇴 징계 기록" },
				{ type: "doc", id: "background-check/colombia-inpec", label: "🇨🇴 INPEC" },
				{ type: "doc", id: "background-check/dea-background-check", label: "🌐 DEA" },
				{ type: "doc", id: "background-check/europol-background-check", label: "🌐 Europol" },
				{ type: "doc", id: "background-check/fbi-background-check", label: "🌐 FBI" },
				{ type: "doc", id: "background-check/interpol-background-check", label: "🌐 Interpol" },
				{ type: "doc", id: "background-check/ofac-background-check", label: "🌐 OFAC" },
				{ type: "doc", id: "background-check/onu-background-check", label: "🌐 ONU" },
			],
		},
	],
};

export default sidebars;
